server:
    port: 9001
    context-path:

spring:
    datasource:
        url: jdbc:mysql://192.168.25.719:3306/shavuot?characterEncoding=UTF-8
        username: kislev_admin
        password: HYyWPe1gFJ5dVo2b7xA5PON6ZHdMpLw
        driver-class-name: com.mysql.jdbc.Driver



